# Simple linear regression - Exercise

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size.csv'. 

You are expected to create a simple linear regression (similar to the one in the lecture), using the new data. 

Apart from that, please:
-  Create a scatter plot (with or without a regression line)
-  Calculate the R-squared
-  Display the intercept and coefficient(s)
-  Using the model make a prediction about an apartment with size 750 sq.ft.

Note: In this exercise, the dependent variable is 'price', while the independent variable is 'size'.

Good luck!

## Import the relevant libraries

In [16]:

import numpy as np
import pandas as pd
from helper.linear_model import LinearRegression
import matplotlib.pyplot as plt 
import seaborn as sns 

sns.set()

ModuleNotFoundError: No module named 'helper'

## Load the data

In [ ]:
data = pd.read_csv("real_estate_price_size (1).csv")
data

price     size
0   234314.144   643.09
1   228581.528   656.22
2   281626.336   487.29
3   401255.608  1504.75
4   458674.256  1275.46
..         ...      ...
95  252460.400   549.80
96  310522.592  1037.44
97  383635.568  1504.75
98  225145.248   648.29
99  274922.856   705.29

[100 rows x 2 columns]

In [ ]:
data.describe() 

price         size
count     100.000000   100.000000
mean   292289.470160   853.024200
std     77051.727525   297.941951
min    154282.128000   479.750000
25%    234280.148000   643.330000
50%    280590.716000   696.405000
75%    335723.696000  1029.322500
max    500681.128000  1842.510000

## Create the regression

### Declare the dependent and the independent variables

In [ ]:
y = data["price"]
x = data["size"].values.reshape(-1, 1)

### Explore the data

In [ ]:
x

array([[ 643.09],
       [ 656.22],
       [ 487.29],
       [1504.75],
       [1275.46],
       [ 575.19],
       [ 570.89],
       [ 620.82],
       [ 682.26],
       [ 694.52],
       [1060.36],
       [1842.51],
       [ 694.52],
       [1009.25],
       [1300.96],
       [1379.72],
       [ 690.54],
       [ 623.94],
       [ 681.07],
       [1027.76],
       [ 620.71],
       [ 549.69],
       [1207.45],
       [ 518.38],
       [ 525.81],
       [1103.3 ],
       [ 570.89],
       [1334.1 ],
       [ 681.07],
       [1496.36],
       [1010.33],
       [ 681.07],
       [ 597.9 ],
       [ 525.81],
       [ 857.54],
       [ 622.97],
       [ 823.21],
       [ 570.25],
       [ 685.48],
       [ 698.29],
       [1021.95],
       [ 682.26],
       [ 823.21],
       [1334.1 ],
       [1060.36],
       [ 698.29],
       [ 633.19],
       [ 698.29],
       [ 633.19],
       [ 617.05],
       [ 647.5 ],
       [1021.95],
       [1021.95],
       [ 727.88],
       [ 647.5 ],
       [15

### Transform the inputs into a matrix (2D object)

### Regression itself

In [ ]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression()

### Calculate the R-squared

In [ ]:
reg.score(x, y)

0.7447391865847586

### Find the intercept

In [ ]:
reg.intercept_

101912.60180122897

### Find the coefficients

In [ ]:
reg.coef_

array([223.17874259])

### Making predictions

You find an apartment online with a size of 750 sq.ft.

All else equal what should be its price according to the model?

In [ ]:
reg.predict([[750]])

array([269296.65874718])